version: "2"

services:

  memcached:
    container_name: memcached
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - so-elastic-net
     
  hive2elastic:
    container_name: hive2elastic
    build: /opt/hive2elastic/hive2elastic
    networks:
      - so-elastic-net
    volumes:
      - /etc/hive2elastic/hive2elastic.conf:/hive2elastic/hive2elastic.conf:ro
      - /etc/hive2elastic/hive2elastic.yaml:/hive2elastic/hive2elastic.yaml:ro

networks:
  so-elastic-net:
    external: true
